//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MLWebEntities : DbContext
    {
        public MLWebEntities()
            : base("name=MLWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactP> ContactP { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<HomeS> HomeS { get; set; }
        public virtual DbSet<HomeA> HomeA { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<AboutPage> AboutPage { get; set; }
        public virtual DbSet<Language> Language { get; set; }
    }
}
