//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string Urunimg { get; set; }
        public string explanation { get; set; }
        public string Lang { get; set; }
        public string Tablo { get; set; }
    }
}
